require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'ModernMilkmanDriver' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])


  target 'ModernMilkmanDriverTests' do
    inherit! :complete
    # Pods for testing
  end

  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'

  pod 'Firebase/Core'

  # ignore console warning, below required for text recognition
  pod 'react-native-camera', path: '../node_modules/react-native-camera', subspecs: [
  'TextDetector'
  ]

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({ 'Flipper-Folly' => '2.3.0' })
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'ModernMilkmanDriver-tvOS' do
  # Pods for ModernMilkmanDriver-tvOS

  target 'ModernMilkmanDriver-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
